-- ============================================================
-- MEMORY MANAGEMENT ONLINE TEST
-- SUPABASE DATABASE
-- ============================================================

create table if not exists public.exam_submissions (
    id bigint generated by default as identity primary key,
    srn text not null,
    student_name text not null,
    section text not null,
    test_title text not null,
    start_time timestamptz not null,
    submit_time timestamptz not null,
    score integer not null,
    total integer not null,
    percentage numeric(5,2) not null,
    answers jsonb not null,
    submitted_by_timeout boolean not null default false
);

-- One attempt per SRN for this examination.
create unique index if not exists unique_exam_srn
on public.exam_submissions (srn);

create index if not exists idx_exam_section
on public.exam_submissions (section);

create index if not exists idx_exam_submit_time
on public.exam_submissions (submit_time);
